import React, { useState, useEffect } from 'react';
import { supabase } from '../../lib/supabase';
import { Edit as EditIcon, Trash as TrashIcon, Plus as PlusIcon, X as XIcon, Check as CheckIcon } from 'lucide-react';
import './ProductManagement.css';

interface Product {
  id: string;
  name: string;
  price: number;
  description: string;
  counter_type: string;
  category_id?: string;
  category?: string;
  image_url?: string;
}

const ProductManagement: React.FC = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [newProduct, setNewProduct] = useState<boolean>(false);
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [filterType, setFilterType] = useState<string>('all');
  
  // Fetch products
  useEffect(() => {
    const fetchProducts = async () => {
      setLoading(true);
      try {
        const { data, error } = await supabase
          .from('products')
          .select('*')
          .order('name');
          
        if (error) {
          throw error;
        }
        
        setProducts(data || []);
      } catch (error) {
        console.error('Error fetching products:', error);
      } finally {
        setLoading(false);
      }
    };
    
    fetchProducts();
  }, []);
  
  // Handle product edit
  const handleEdit = (product: Product) => {
    setEditingProduct({ ...product });
    setNewProduct(false);
  };
  
  // Handle product delete
  const handleDelete = async (id: string) => {
    if (!window.confirm('Are you sure you want to delete this product?')) {
      return;
    }
    
    try {
      const { error } = await supabase
        .from('products')
        .delete()
        .eq('id', id);
        
      if (error) {
        throw error;
      }
      
      // Update local state
      setProducts(products.filter(product => product.id !== id));
    } catch (error) {
      console.error('Error deleting product:', error);
    }
  };
  
  // Handle save (create or update)
  const handleSave = async () => {
    if (!editingProduct) return;
    
    try {
      if (newProduct) {
        // Create new product
        const { data, error } = await supabase
          .from('products')
          .insert([editingProduct])
          .select();
          
        if (error) {
          throw error;
        }
        
        // Update local state
        setProducts([...products, data[0]]);
      } else {
        // Update existing product
        const { data, error } = await supabase
          .from('products')
          .update(editingProduct)
          .eq('id', editingProduct.id)
          .select();
          
        if (error) {
          throw error;
        }
        
        // Update local state
        setProducts(products.map(product => 
          product.id === editingProduct.id ? data[0] : product
        ));
      }
      
      // Reset editing state
      setEditingProduct(null);
      setNewProduct(false);
    } catch (error) {
      console.error('Error saving product:', error);
    }
  };
  
  // Handle cancel
  const handleCancel = () => {
    setEditingProduct(null);
    setNewProduct(false);
  };
  
  // Handle add new product
  const handleAddNew = () => {
    setEditingProduct({
      id: '', // Will be generated by Supabase
      name: '',
      price: 0,
      description: '',
      counter_type: 'coffee', // Default value
      category_id: '',
      image_url: ''
    });
    setNewProduct(true);
  };
  
  // Handle form field changes
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    if (!editingProduct) return;
    
    const { name, value } = e.target;
    
    // Handle price as a number
    if (name === 'price') {
      setEditingProduct({
        ...editingProduct,
        [name]: parseFloat(value) || 0
      });
    } else {
      setEditingProduct({
        ...editingProduct,
        [name]: value
      });
    }
  };
  
  // Filter products based on search term and filter type
  const filteredProducts = products.filter(product => {
    const matchesSearch = product.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         product.description.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesFilter = filterType === 'all' || product.counter_type === filterType;
    
    return matchesSearch && matchesFilter;
  });
  
  return (
    <div className="product-management">
      {/* Search and Filter */}
      <div className="product-controls">
        <div className="search-bar">
          <input
            type="text"
            placeholder="Search products..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </div>
        
        <div className="filter-controls">
          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
            className="filter-select"
          >
            <option value="all">All Types</option>
            <option value="coffee">Coffee</option>
            <option value="food">Food</option>
            <option value="bar">Bar</option>
          </select>
          
          <button
            onClick={handleAddNew}
            className="btn-add"
            disabled={!!editingProduct}
          >
            <PlusIcon size={16} />
            <span>Add Product</span>
          </button>
        </div>
      </div>
      
      {/* Product List */}
      {loading ? (
        <div className="loading-state">
          <div className="spinner"></div>
          <p>Loading products...</p>
        </div>
      ) : (
        <div className="product-list">
          <table className="product-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Counter Type</th>
                <th>Description</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredProducts.map(product => (
                <tr key={product.id}>
                  <td>{product.name}</td>
                  <td>${product.price.toFixed(2)}</td>
                  <td>
                    <span className={`counter-badge ${product.counter_type}`}>
                      {product.counter_type}
                    </span>
                  </td>
                  <td className="description-cell">{product.description}</td>
                  <td>
                    <div className="action-buttons">
                      <button
                        onClick={() => handleEdit(product)}
                        className="btn-icon"
                        title="Edit"
                      >
                        <EditIcon size={16} />
                      </button>
                      <button
                        onClick={() => handleDelete(product.id)}
                        className="btn-icon delete"
                        title="Delete"
                      >
                        <TrashIcon size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      
      {/* Edit Modal */}
      {editingProduct && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-header">
              <h3>{newProduct ? 'Add New Product' : 'Edit Product'}</h3>
              <button onClick={handleCancel} className="btn-icon">
                <XIcon size={20} />
              </button>
            </div>
            
            <div className="modal-body">
              <div className="form-group">
                <label htmlFor="name">Product Name</label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={editingProduct.name}
                  onChange={handleChange}
                  required
                />
              </div>
              
              <div className="form-group">
                <label htmlFor="price">Price ($)</label>
                <input
                  type="number"
                  id="price"
                  name="price"
                  value={editingProduct.price}
                  onChange={handleChange}
                  step="0.01"
                  min="0"
                  required
                />
              </div>
              
              <div className="form-group">
                <label htmlFor="counter_type">Counter Type</label>
                <select
                  id="counter_type"
                  name="counter_type"
                  value={editingProduct.counter_type}
                  onChange={handleChange}
                  required
                >
                  <option value="coffee">Coffee</option>
                  <option value="food">Food</option>
                  <option value="bar">Bar</option>
                </select>
              </div>
              
              <div className="form-group">
                <label htmlFor="description">Description</label>
                <textarea
                  id="description"
                  name="description"
                  value={editingProduct.description}
                  onChange={handleChange}
                  rows={3}
                />
              </div>
              
              <div className="form-group">
                <label htmlFor="image_url">Image URL (optional)</label>
                <input
                  type="text"
                  id="image_url"
                  name="image_url"
                  value={editingProduct.image_url || ''}
                  onChange={handleChange}
                />
              </div>
            </div>
            
            <div className="modal-footer">
              <button onClick={handleCancel} className="btn-secondary">
                Cancel
              </button>
              <button onClick={handleSave} className="btn-primary">
                <CheckIcon size={16} />
                <span>{newProduct ? 'Create Product' : 'Save Changes'}</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ProductManagement;
