import React, { useState, useEffect } from 'react';
import { supabase } from '../../lib/supabase';
import { Edit as EditIcon, Trash as TrashIcon, Plus as PlusIcon, X as XIcon, Check as CheckIcon } from 'lucide-react';
import './StaffManagement.css';

interface StaffMember {
  id: string;
  email: string;
  name: string;
  role: string;
  counter_type: string;
  created_at?: string;
}

const StaffManagement: React.FC = () => {
  const [staff, setStaff] = useState<StaffMember[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [editingStaff, setEditingStaff] = useState<StaffMember | null>(null);
  const [newStaff, setNewStaff] = useState<boolean>(false);
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [filterType, setFilterType] = useState<string>('all');
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  
  // Fetch staff members
  useEffect(() => {
    const fetchStaff = async () => {
      setLoading(true);
      try {
        const { data, error } = await supabase
          .from('users')
          .select('*')
          .order('name');
          
        if (error) {
          throw error;
        }
        
        setStaff(data || []);
      } catch (error) {
        console.error('Error fetching staff:', error);
        setError('Failed to load staff members');
      } finally {
        setLoading(false);
      }
    };
    
    fetchStaff();
  }, []);
  
  // Handle staff edit
  const handleEdit = (staffMember: StaffMember) => {
    setEditingStaff({ ...staffMember });
    setNewStaff(false);
    setError(null);
    setSuccess(null);
  };
  
  // Handle staff delete
  const handleDelete = async (id: string) => {
    if (!window.confirm('Are you sure you want to delete this staff member?')) {
      return;
    }
    
    try {
      const { error } = await supabase
        .from('users')
        .delete()
        .eq('id', id);
        
      if (error) {
        throw error;
      }
      
      // Update local state
      setStaff(staff.filter(member => member.id !== id));
      setSuccess('Staff member deleted successfully');
    } catch (error) {
      console.error('Error deleting staff member:', error);
      setError('Failed to delete staff member');
    }
  };
  
  // Handle save (create or update)
  const handleSave = async () => {
    if (!editingStaff) return;
    
    try {
      if (newStaff) {
        // Create new staff member
        const { data, error } = await supabase
          .from('users')
          .insert([editingStaff])
          .select();
          
        if (error) {
          throw error;
        }
        
        // Update local state
        setStaff([...staff, data[0]]);
        setSuccess('Staff member created successfully');
      } else {
        // Update existing staff member
        const { data, error } = await supabase
          .from('users')
          .update(editingStaff)
          .eq('id', editingStaff.id)
          .select();
          
        if (error) {
          throw error;
        }
        
        // Update local state
        setStaff(staff.map(member => 
          member.id === editingStaff.id ? data[0] : member
        ));
        setSuccess('Staff member updated successfully');
      }
      
      // Reset editing state
      setEditingStaff(null);
      setNewStaff(false);
    } catch (error) {
      console.error('Error saving staff member:', error);
      setError('Failed to save staff member');
    }
  };
  
  // Handle cancel
  const handleCancel = () => {
    setEditingStaff(null);
    setNewStaff(false);
    setError(null);
  };
  
  // Handle add new staff
  const handleAddNew = () => {
    setEditingStaff({
      id: '', // Will be generated by Supabase
      email: '',
      name: '',
      role: 'staff',
      counter_type: 'coffee'
    });
    setNewStaff(true);
    setError(null);
    setSuccess(null);
  };
  
  // Handle form field changes
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    if (!editingStaff) return;
    
    const { name, value } = e.target;
    setEditingStaff({
      ...editingStaff,
      [name]: value
    });
  };
  
  // Filter staff based on search term and filter type
  const filteredStaff = staff.filter(member => {
    const matchesSearch = 
      member.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      member.email.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesFilter = 
      filterType === 'all' || 
      member.role === filterType || 
      member.counter_type === filterType;
    
    return matchesSearch && matchesFilter;
  });
  
  return (
    <div className="staff-management">
      {/* Search and Filter */}
      <div className="staff-controls">
        <div className="search-bar">
          <input
            type="text"
            placeholder="Search staff..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </div>
        
        <div className="filter-controls">
          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
            className="filter-select"
          >
            <option value="all">All Staff</option>
            <option value="admin">Administrators</option>
            <option value="staff">Staff Members</option>
            <option value="coffee">Coffee Counter</option>
            <option value="food">Food Counter</option>
            <option value="bar">Bar Counter</option>
          </select>
          
          <button
            onClick={handleAddNew}
            className="btn-add"
            disabled={!!editingStaff}
          >
            <PlusIcon size={16} />
            <span>Add Staff</span>
          </button>
        </div>
      </div>
      
      {/* Error and Success Messages */}
      {error && (
        <div className="alert error">
          <XIcon size={16} />
          <span>{error}</span>
        </div>
      )}
      
      {success && (
        <div className="alert success">
          <CheckIcon size={16} />
          <span>{success}</span>
        </div>
      )}
      
      {/* Staff List */}
      {loading ? (
        <div className="loading-state">
          <div className="spinner"></div>
          <p>Loading staff members...</p>
        </div>
      ) : (
        <div className="staff-list">
          <table className="staff-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Counter Type</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredStaff.length === 0 ? (
                <tr>
                  <td colSpan={5} className="no-results">No staff members found</td>
                </tr>
              ) : (
                filteredStaff.map(member => (
                  <tr key={member.id}>
                    <td>{member.name}</td>
                    <td>{member.email}</td>
                    <td>
                      <span className={`role-badge ${member.role}`}>
                        {member.role}
                      </span>
                    </td>
                    <td>
                      <span className={`counter-badge ${member.counter_type}`}>
                        {member.counter_type}
                      </span>
                    </td>
                    <td>
                      <div className="action-buttons">
                        <button
                          onClick={() => handleEdit(member)}
                          className="btn-icon"
                          title="Edit"
                        >
                          <EditIcon size={16} />
                        </button>
                        <button
                          onClick={() => handleDelete(member.id)}
                          className="btn-icon delete"
                          title="Delete"
                        >
                          <TrashIcon size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}
      
      {/* Edit Modal */}
      {editingStaff && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-header">
              <h3>{newStaff ? 'Add New Staff Member' : 'Edit Staff Member'}</h3>
              <button onClick={handleCancel} className="btn-icon">
                <XIcon size={20} />
              </button>
            </div>
            
            <div className="modal-body">
              <div className="form-group">
                <label htmlFor="name">Full Name</label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={editingStaff.name}
                  onChange={handleChange}
                  required
                />
              </div>
              
              <div className="form-group">
                <label htmlFor="email">Email</label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={editingStaff.email}
                  onChange={handleChange}
                  required
                />
              </div>
              
              <div className="form-group">
                <label htmlFor="role">Role</label>
                <select
                  id="role"
                  name="role"
                  value={editingStaff.role}
                  onChange={handleChange}
                  required
                >
                  <option value="staff">Staff</option>
                  <option value="admin">Administrator</option>
                </select>
              </div>
              
              <div className="form-group">
                <label htmlFor="counter_type">Counter Type</label>
                <select
                  id="counter_type"
                  name="counter_type"
                  value={editingStaff.counter_type}
                  onChange={handleChange}
                  required
                  disabled={editingStaff.role === 'admin'}
                >
                  <option value="coffee">Coffee Counter</option>
                  <option value="food">Food Counter</option>
                  <option value="bar">Bar Counter</option>
                </select>
                <small className="help-text">
                  Staff will only see orders for products from their assigned counter category.
                  Admins can access all counters.
                </small>
              </div>
            </div>
            
            <div className="modal-footer">
              <button onClick={handleCancel} className="btn-secondary">
                Cancel
              </button>
              <button onClick={handleSave} className="btn-primary">
                <CheckIcon size={16} />
                <span>{newStaff ? 'Create Staff' : 'Save Changes'}</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default StaffManagement;
